# Generated by Django 5.1.6 on 2025-02-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default='web', max_length=100, verbose_name='Tipo'),
        ),
    ]
