# Generated by Django 5.1.6 on 2025-02-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='blog/pdfs'),
        ),
    ]
