# Generated by Django 5.1.6 on 2025-03-12 19:40

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
